### ISSUE TITLE
line 7, 1st character : Object expected

### ISSUE THREAD

**Issue by YouHaveTrouble** [rannmann/node-steam-trade-tutorial#2]
I don't know s**\* about javascript, but i want to learn it while making steam bot. Can you explain why I get this error?

Line: 7
Character: 1
Error: Object expected
Error code is 800A138F

**Comment by rannmann** [comment]
You didn't install the dependencies.  If you cloned this repo, just type `npm install` in your project's directory and all the dependencies will install automatically.  If not, you  need to `npm install steam` to resolve the line 7 issue.

**Comment by YouHaveTrouble** [comment]
http://i.imgur.com/0f5oDZi.png

I might be missing something, but I have git for sure

**Comment by rannmann** [comment]
Try `npm install git://github.com/seishun/node-steam-trade.git`.  If that doesn't work, then git is most likely not in your PATH.  If you installed the Windows GitHub client, check out this thread: https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows

**Comment by YouHaveTrouble** [comment]
Problem solved. Git errored during installation and I didn't noticed it. Reinstaling git helped.
